name: qr_attendance
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_form_builder: ^9.1.0
  bootstrap_icons: ^1.10.5+2
  form_builder_validators: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_slidable: ^3.0.0
  quickalert: ^1.0.2
  status_alert: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.3
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  curved_navigation_bar: ^1.0.3
  modern_form_line_awesome_icons: ^2.0.1
  cloud_firestore: ^4.9.3
  pretty_qr_code: ^3.0.0
  qr_code_scanner: ^1.0.1
  audioplayers: ^5.2.0
  fk_toggle: ^0.1.4
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  screenshot: ^2.1.0
  calendar_date_picker2: ^0.5.3
  filter_list: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/dvclogo.png
  image_dark: assets/images/dvclogo.png

  android_12:
    image: assets/images/dvclogo.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/dvclogo.png
    icon_background_color_dark: "#272727"


  flutter_lints: ^2.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/


